### ISSUE TITLE
ruleのmetaのdocsについて

### ISSUE THREAD

**Issue by tyankatsu0105** [eslint/eslint-jp#10]
質問です。

rule作成時にexportするobjectのmetaプロパティに関してです。
`docs`にdescriptionやurlなど書くと思うのですが、これを書く書かないとでlintの挙動は変わりますか？
いまいちこの`docs`の役割が分かっていません。
`docs/rules/xxx.md`というようにdocsは書くと思うので、不要だなと思ってます。

どうでしょう？

**Comment by tyankatsu0105** [comment]
あ、docsは省略可能って説明ありますね。
でも書く場合はなんのために書くんでしょう？？

**Comment by mysticatea** [comment]
返答遅くなりました。

`docs` は動作に影響しません。一部のツール (エディタ拡張など) が利用する情報です。

**Comment by tyankatsu0105** [comment]
ありがとうございます。
