### ISSUE TITLE
Vue 向けのスマートな custom rule の実装について

### ISSUE THREAD

**Issue by kazupon** [eslint/eslint-jp#11]
質問です。

## 聞きたいこと
今、Vue 向けに、i18n の custom rule を 作っているのですが、`.vue`と`.(j|t)s` (SFC と SFC 以外のJavaScript/TypeScript) の両方に対応した custome rule 作りたい。

## 困っていること
`.vue` の方の custom rule は[`vue-eslint-parser`のこちら](https://github.com/mysticatea/vue-eslint-parser#-usage-for-custom-rules--plugins)ドキュメントにあるように、`context.parserServices` を使って、custome rule を実装したオブジェクトを return すれば、`.vue` 向けに対応できます。

ただ、このようにしてしまうと、`.(j|t)s` のJavaScript/TypeScriptのコードには lint が対応できなくなってしまう。

## 自分が今考えてる問題の解決方法
`context.getFilename()`で取得したファイル名の拡張子を見て、動的に custome rule の実装オブジェクトを返す。

```js
module.exports = {
  // ...
  create (context) {
    const filename = context.getFilename()
    if (isSFCFile(filename)) {
      return context.parserServices.defineTemplateBodyVisitor({
        // Event handlers for <template> ...
      }, {
        // Event handlers for <script> ...
      })
    } else {
      return {
        // Evant Handlers for normally ...
      }
    }
  }
}

function isSFCFile (filename) {
  // ...
}
```

ESLintのAPIか何かで、スマートな方法があれば教えて頂けるとありがたいです。:pray:

**Comment by mysticatea** [comment]
`context.parserServices.defineTemplateBodyVisitor` の第2引数は、`.vue` ファイルでない場合は通常のスクリプトをチェックするために使われます。なので、

```js
module.exports = {
  // ...
  create (context) {
    return context.parserServices.defineTemplateBodyVisitor({
      // Event handlers for <template> ...
    }, {
      // Event handlers for scripts ...
    });
  }
}
```

こんな感じで良いはずです。

**Comment by kazupon** [comment]
@mysticatea 
早速ありがとうございます！
第2引数に指定したら動作しました。
[こちらのastのドキュメント](https://github.com/mysticatea/vue-eslint-parser/blob/master/docs/ast.md)には、 `Event handlers for <script>` と書いてあったので、てっきりSFCの`<script>`以外は使えないのかと思いました。

もし、ドキュメントがuncorrectなら、こちらでPR送っておきたいと思います。 :)

**Comment by kazupon** [comment]
こちら解決したので、閉じます。
ありがとうございました！
