### ISSUE TITLE
【Vue】【Gridsome】nodeに必須なattributeがあるか確認する術

### ISSUE THREAD

**Issue by tyankatsu0105** [eslint/eslint-jp#12]
# やりたいこと
`<g-image>` には`src` or `:src` が必須なので、それがなければ`g-image`のlocに「srcは必須だよ」的なエラーメッセージを入れたい

# 悩んでいること
- `g-image`のlocを取得しつつ、`VIdentifier` の値をチェックする上手い方法が思いつかない
- 下記のようにループを回してチェックする方法になるのかなーと考えてます
```
"VElement[name='g-image']"(node){
  const loc = node.loc

  for(const attribute of node.startTag.attributes){
    if(attribute.key.argument.name === 'src') {
      // ...
    }
  }
},
```

**Comment by mysticatea** [comment]
そうですね。素直に書くとループを回してチェックすることになります。実際、`eslint-plugin-vue` にも[こんな感じのユーティリティ](https://github.com/vuejs/eslint-plugin-vue/blob/b7ee76e8d89232775c43bea2bf23dae780a90a15/lib/utils/index.js#L159-L229)があります。

古典的な ESLint の手法 (※1) ではスタックを使います。その場合はこんな感じ

```js
let stack = null;

return {
    // 入口でスタックを積む
    "VElement"(node) {
        stack = {
            upper: stack,
            srcExists: false
        }
    },
    
    // 出口でスタックを下ろして確認・報告する
    "VElement:exit"(node) {
        const { srcExists } = stack;
        stack = stack.upper;

        if (!srcExists && node.name === "g-image") {
            context.report({ node, messageId: "requireSrc" })
        }
    },
    
    // 現在のスタックに情報を記録する。
    [[
        "VAttribute[directive=false][name='src']",
        "VAttribute[directive=true][name='bind'][argument='src']"
    ]](node) {
        stack.srcExists = true;
    },
};
```

※1: 最近はルーズになっていますが、昔は性能のために AST をループで確認することは禁じ手でした。

**Comment by tyankatsu0105** [comment]
ありがとうございます！
早速真似てやってみます！！

**Comment by tyankatsu0105** [comment]
@mysticatea 
`eslint-plugin-vue`のutilsを使って実装してみました。
https://github.com/gridsome/eslint-plugin-gridsome/pull/6/files#diff-496867cc81b1f9c3c5120bfe2adc0be2R32

ですが、`hasDirective`の挙動がよく分かってなくて、条件にうまく当てはまらないです・・・
`src`と`:src`が`g-image`にない場合にエラーを出すというルール予定です。

**Comment by ota-meshi** [comment]
こんにちは
vue-eslint-parserのバージョンはeslint-plugin-vueの依存バージョンと一致していますか？
vue-eslint-parserの最新版はVue2.6の対応でASTに大きな変更が入りました。
しかし、現在リリースされているeslint-plugin-vueの最新版はまだこのvue-eslint-parserの最新版に対応していなかったと思います。

**Comment by tyankatsu0105** [comment]
@ota-meshi 
なるほど！そっちは試してなかったです！
確かにutilsをrequireせずに手元にコピーして試してみると挙動が違ったのでそこらへんかもしれないです！！
ちょっとやってみます。
ありがとうございます。

**Comment by tyankatsu0105** [comment]
`eslint-plugin-vue`をremoveし、`eslint-plugin-vue/lib/utils`をコピーしてみたのですが、結果は同じでした。
https://github.com/gridsome/eslint-plugin-gridsome/pull/6/commits/37bc64064e71d9e736011114c6a20cfbe8163eb6

`hasAttribute`と`hasDirective`をそれぞれ個別に実行してみると、
```
<template>
  <div>
    <g-image :src="foo.bar" />
    <g-image src="foo.bar" />
    <g-image :src="foo.bar" />
    <g-image :width="foo.bar" />
  </div>
</template>
```

```js
create (context) {
  return utils.defineTemplateBodyVisitor(context, {
    "VElement[name='g-image']" (node) {
      console.log(JSON.stringify(!utils.hasAttribute(node, 'src'), replacer, 2));
    }
  })
}
```

```
true
false
true
true
```

```js
create (context) {
  return utils.defineTemplateBodyVisitor(context, {
    "VElement[name='g-image']" (node) {
      console.log(JSON.stringify(!utils.hasDirective(node, 'bind', 'src')));
    }
  })
}
```

```
false
true
false
true
```

となり、こちらの期待した通りの結果が返ってきています。
しかし、 `||` でつなげると、

```js
create (context) {
  return utils.defineTemplateBodyVisitor(context, {
    "VElement[name='g-image']" (node) {
      console.log(JSON.stringify(!utils.hasAttribute(node, 'src') || !utils.hasDirective(node, 'bind', 'src'), replacer, 2));
    }
  })
}
```

```
true
true
true
true
```

となり、期待した
```
false
false
false
true
```
が返ってきません。

**Comment by ota-meshi** [comment]
&&でつなげるのが正しいような気がします。

**Comment by tyankatsu0105** [comment]
おっと・・・
失礼しました・・・
できました。ありがとうございます。
