### ISSUE TITLE
lib index?の型に関して

### ISSUE THREAD

**Issue by tyankatsu0105** [eslint/eslint-jp#13]
https://github.com/tyankatsu0105/eslint-plugin/blob/develop/lib/index.ts
この箇所にあたる型が見当たらないのですが、ご存知でしょうか？

https://eslint.org/docs/developer-guide/architecture
ここでいうCLIEngineのことかなって思ってます。

typescript-eslintにも型を定義している様子がないですし、
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/index.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts
にも特に見当たりません・・・

**Comment by tyankatsu0105** [comment]
なんとなく、こういうことがしたいなーという感じです。

```ts
// lib/util/createLibIndex.ts
type CreateLibIndex = {
  rules: {
    [k: string]: any;
  };
};
export const createLibIndex = ({ rules }: CreateLibIndex) => ({ rules });
```

```ts
// lib/index.ts
import { createLibIndex } from "./util";

import { rules } from "./rules";

export = createLibIndex({
  rules
});
```

**Comment by mysticatea** [comment]
型としては[これ](https://github.com/eslint/eslint/blob/master/lib/shared/types.js#L137-L143)ですが、後はもう ESLint 側が読むだけの場所なので、今までユーザーランドでその型を使いたい人がいなかったのかもですね。

**Comment by tyankatsu0105** [comment]
なるほど、ありがとうございます。
typescript-eslintチームでもこの箇所に関しては特に話題に上がらなかったんでしょうか？
[experimental-utils](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/experimental-utils)で型をちゃんとしている感じがあるので、どうなんだろうと疑問に思いました。

**Comment by mysticatea** [comment]
私はtypescript-eslintチームではないのでなんとも 😅
今無いということはそうなんだと思います。ブラウザで使うことを考えるとfs依存したくないですし、スクリプト生成が多いのではないかしら。

**Comment by tyankatsu0105** [comment]
>スクリプト生成が多い

なるほど確かに。
ありがとうございました！！
