### ISSUE TITLE
共有設定のpluginについて

### ISSUE THREAD

**Issue by toshi-toma** [eslint/eslint-jp#14]
[Qiitaの記事のプラグインの読込元ディレクトリが変わります](https://qiita.com/mysticatea/items/0931a7d910fcb91733ee#%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%AE%E8%AA%AD%E8%BE%BC%E5%85%83%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%8C%E5%A4%89%E3%82%8F%E3%82%8A%E3%81%BE%E3%81%99)の箇所で

> ⚠️ 共有設定に書かれた plugins 設定のプラグインは、それを extends する利用元の .eslintrc.* ファイルの場所を基準に読み込まれます。そのため、共有設定からプラグインを利用する場合は引き続き peerDependencies を利用する必要があります。

と書かれているのですが

共有設定でプラグインを利用している場合、そのpluginは必ずpeerDependenciesにしなければいけないのでしょうか？

私が作っている共有設定は、利用者がpluginをインストールしなくても利用できるように`dependencies`にしています。
- [package.json](https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/blob/8b0d71b5d468a94017e45b6d67c32d9e5c62549f/package.json#L30-L40)
- [共有設定](https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/blob/master/index.js)

現状起きている問題として、peerDependenciesにしないと、Monorepoスタイルのプロジェクトでこの共有設定を利用する場合、うまくpluginが読み込めないのが問題なのかな？と思ったのですが、認識は間違ってますでしょうか？

**Comment by mysticatea** [comment]
> 共有設定でプラグインを利用している場合、そのpluginは必ずpeerDependenciesにしなければいけないのでしょうか？

はい、その通りです。

これは[現在 open されている最も古い Issue](https://github.com/eslint/eslint/issues/3458) の話になります。本来、共有設定がプラグインを利用する場合、`depvendencies` にプラグインを書いても正常に利用できません。Monorepo は関係ありません。常に、です。

例えば、次のような依存ツリーがある場合:

```
my-project
├ eslint
└ eslint-config-foo
  └ eslint-plugin-bar
```

`eslint-plugin-bar` は `eslint-config-foo` の依存パッケージ (`dependencies`) なので、`eslint-config-foo` の中で `require("eslint-plugin-bar")` と書けば、それが正常に読み込めます。
しかし、`eslint-plugin-bar` は `my-project` の依存パッケージ (`dependencies`) ではないので、`my-project` のコードの中で `require("eslint-plugin-bar")` と書くと、本来は `MODULE_NOT_FOUND` エラーになります。ESLint は `my-project` のコードの中で `require("eslint-plugin-bar")` と書いたかのようにプラグインを読み込むので、つまり、ESLint はプラグインの読み込みに失敗します。

一方、`eslint-plugin-bar` が `eslint-config-foo` のピア依存パッケージ (`peerDependencies`) であれば、npm は `eslint-config-foo` の利用者 (この例では `my-project`) から `eslint-plugin-bar` を利用できるようにします (npm 3.x から 6.x では自動でしてくれませんが。npm 2.x と 7.x では自動でしてくれます)。これなら、ESLint は共有設定のプラグインを読むことができます。

しかし実際には、npm 3.x 以降では重複排除 (dedupe) という仕組みの副作用として、偶然、`my-project` のコードの中で `require("eslint-plugin-bar")` と書いて正常に読み込めることが多いです。仕様的にはエラーになるはずですが、表面上は正常に動いているように見えます。

重複排除 (dedupe) の副作用のために偶然 動いているだけなので、重複排除 (dedupe) の振る舞いを変更するオプション `--global-style` や `--legacy-bundling` を使ってインストールすると、(仕様通りに) ESLint がプラグインの読み込みに失敗する様子を見ることができるハズです。

**Comment by toshi-toma** [comment]
いまはdedupeの副作用で正常に動いてるように見える & dedupeの振る舞いを変更するにインストールしたり、ユーザーが共有設定で求めてるバージョンとは違うpluginのバージョンを個別にインストールしていた場合などを考えると`peerDependencies`にしないといけない。

など理解できました。助かりました。ありがとうございます！🙇‍♂️

**Comment by toshi-toma** [comment]
RFC👀
https://github.com/eslint/rfcs/pull/9
