### ISSUE TITLE
@types/eslint の RuleModule.create 関数で JSX 系の型情報がエラーになる

### ISSUE THREAD

**Issue by uttk** [eslint/eslint-jp#15]
こんにちは！
現在、ESLint プラグインを TypeScript を用いて自作しているのですが、JSX 系の型情報が`@types/eslint`に無い様子です。
参考までに以下のソースコードを示します。

```ts
/**
 * バージョン情報
 * eslint: "^7.3.1"
 * @types/eslint: "^7.2.0"
 * @types/estree-jsx: "^0.0.0"
 */
import { Rule } from "eslint";
import { Node, JSXOpeningElement } from "estree-jsx";

// エラーになるサンプルルール
export const ErrorSampleRule: Rule.RuleModule = {
  create: (context) => {
    return {
      // 以下のように型定義したいが、型チェックでエラーになる
      JSXOpeningElement: (node: JSXOpeningElement) => {
        context.report({
          node,
          message: "JSXが使われています",
        });
      },
    };
  },
};

// エラーにならないサンプルルール
export const NonErrorSampleRule: Rule.RuleModule = {
  create: (context) => {
    return {
      // 現状での型定義。型チェックでエラーにならない
      JSXOpeningElement: (node: Node) => {
        if (node.type === "JSXOpeningElement") {
          context.report({
            node,
            message: "JSXが使われています",
          });
        }
      },
    };
  },
};
```

上記のソースコードのように、`JSXOpeningElement`のような関数の引数に AST ノードの型を定義したいのですが、現状だと型チェックの段階でエラーになります。

これを定義できるようにすることは可能でしょうか？
もしくは、JSX 系は素の ESLint Parser ではなく、別の Parser などを使うべきでしょうか？

よろしくお願いします。

**Comment by mysticatea** [comment]
こんにちは！

`@types/eslint` はコアメンバーによって管理されているものではないので、ちょっと信用度が低いかもしれません。
見ると、`@types/estree` に依存しているようなので、確かに JSX の型は無さそうですね。

`@typescript-eslint` の型定義を使うのがより良いと思います。[@typescript-eslint/types](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/types) が AST の型を持っています。また、[@typescript-eslint/experimental-utils](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/experimental-utils) がルール定義のためのユーティリティを提供しています。 `@typescript-eslint` 内のルールを見ると使い方は分かるかと思います。

**Comment by uttk** [comment]
@mysticatea 

有益な情報ありがとうございます！

なるほど、`@types/eslint`って別の人たちが管理されてたんですね。無知で申し訳ないです。。。
[@typescript-eslint/experimental-utils](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/experimental-utils)を使う方が良さそうに感じたので、こちらを使おうと思います。

お忙しい中、対応して頂きありがとうございます。
