### ISSUE TITLE
使用されていないdependencyを検知する方法について

### ISSUE THREAD

**Issue by watilde** [eslint/eslint-jp#2]
こんにちは :wave: 

つい最近 npm にて、使われていないdependencyがあったのを発見したんですが、手動で探したのでとても大変でした。。eslint で、`package.json` に記述されている(dev)dependencyが `require` / `import` されていないのを検知する方法はありますでしょうか？

**Comment by mysticatea** [comment]
こんにちは!

これは ESLint では難しそうですね。
逆 (require() したものが package.json に存在するかチェック) は書いたのですが...
- ESLint は JSON パーサーを持っていないため、JSON ファイルを警告するにはプラグインが必要です。
  以前見つけた [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json) は、内部で JSHint を使ってるという強者でした。
- ESLint はファイル単位での検証になるので、全体で使われているものを集計するという用途には向いていません (エディタで動いている時にどうするかとか...)。

AST を使うとすると `globby`, `acorn`, `escope` あたりを使うとわりと簡単に書けそうな気はします。
あるいは.... 検索すると [unused-deps](https://www.npmjs.com/package/unused-deps) が見つかりました。シンプルに正規表現でチェックしているようです。

... ESLint はフィットしていないと思いますが、 package.json の健全性をチェックするツールというのは、良さそうなアイデアですね。
`bin` フィールドに指定したファイルが `#!/usr/bin/env node` を持っているかどうか、npm-scripts の中で無駄な `node_modules/.bin/` プレフィックスを付けてないか、足りないフィールドはないか、不要な依存がないかなど、いろいろ調べられそうです。

**Comment by watilde** [comment]
これ、とても合点が行きました。

> ESLint はファイル単位での検証になるので

ひとまず `unused-deps` で解決できそうでした :)
Thank you so much!
