### ISSUE TITLE
quotes: 「'」と「"」を両方使用しているとき「`」を使用すると出る警告について

### ISSUE THREAD

**Issue by 59naga** [eslint/eslint-jp#3]
こんにちは、素敵な場所を提供いただき有難うございます。早速ですが１件

``` js
it(`if opts.value is "serial",  and script doesn't exist, should handle the script as a shell command`, () => {
```

``` bash
$ npm run lint
#  60:9  error    Strings must use singlequote                    quotes
```

[Enforce Quote Style (quotes)](http://eslint.org/docs/rules/quotes)で質問…というより要望ですが、上記のようなコードで出る警告を回避する方法は
1. `// eslint-disable-next-line quotes`を使用して、警告機能自体を停止する
2. 「`\"`」か「`\'`」をエスケープして、エスケープした引用符で囲む
以上でしょうか？

そうであれば、時間がある時にPRを書いてみたいのですが、英語が苦手なのでその辺が心配です…。

**Comment by mysticatea** [comment]
Thank you for this issue.

`quotes` ルールは3種類オプションがあるのに、`avoid-escape`ではバックチックを扱っていないというのは、やっぱり変ですよね。現在のところ、その警告を回避する手段は、その2種類であっています。

実は、これについては eslint/eslint#5234 でオプションの追加が提案されていて、 eslint/eslint#5661 に PR があります。提案は紆余曲折あったようですが、最終的に `{"avoidEscape": true, "allowTemplateLiterals": true}` のようなオプションになったようです。
おそらく次のバージョンで追加されると思いますので、お待ちください :smile:

**Comment by 59naga** [comment]
了解です、お待ちしています！ 👍
