### ISSUE TITLE
エスケープシーケンス文字が含まれる場合のquotesルールについて

### ISSUE THREAD

**Issue by AT-AT** [eslint/eslint-jp#4]
こんにちは！（ESLint最高です）

タイトルの件ですが、シングルクォートのみを使用するルールの場合、文字列中にエスケープシーケンスを含めるためにダブルクォートを使用すると、v3.17.0 ではエラー扱いになるかと思います。

```js
/*eslint quotes: ["error", "single", { "avoidEscape": true }]*/

//✔ GOOD
var foo = 'foo';

//✘ BAD
var foo = "foo\n";
```

テンプレートリテラルの使用が可能な（または許可されている）場合はそれで対応も可能ではありますが、

```js
/*eslint quotes: ["error", "single", { "avoidEscape": true , "allowTemplateLiterals": true }]*/

//✔ GOOD
var foo = `foo\n`;
```

`avoidEscape` 同様、エスケープシーケンス文字を表現する場合は例外とするオプションがあっても良いのではと考えています。

このような扱いなのは、何か作法やベストプラクティスに関連した理由があるのでしょうか？

**Comment by mysticatea** [comment]
こんにちは!

私は quotes ルールに関わっていなかったのですが、テンプレートリテラルが追加された時に一悶着あったようですね。こちらが当時のスレッドです: https://github.com/eslint/eslint/issues/5234

どうやら結論は、

- `quotes` ルールは、テンプレート リテラルを文字列と同等に扱うべきではない。
- テンプレート リテラルを単なる文字列として扱いたいというレアケースのために `allowTemplateLiterals` オプションを追加する。細かい制御がしたい場合は別ルール (プラグイン) で。

ということみたいです。

----

> 文字列中にエスケープシーケンスを含めるためにダブルクォートを使用する

ちょっとこの表現に違和感がありましたので蛇足を。
`quotes` ルールは、

- (エスケープの有無にかかわらず) **シングルクォートとダブルクォートの文字列を混在させない。どちらかに統一する。**

ことを目的としたルールです。ただし、文字列中に同種のクォートが出現すると見づらいので、その場合に限って混在を許可するオプション `avoidEscape` があります。

**avoidEscape オプションがあると...**

```js
/*eslint quotes: [error, double, {avoidEscape: true}] */
let div = "<div class=\"test\"></div>"; // \" が醜いので、
let div = '<div class="test"></div>';   // 文字列中に " があるときだけシングルクォートを許可
```

**avoidEscape オプションがないと...**

```js
/*eslint quotes: [error, double] */
let div = "<div class=\"test\"></div>"; // GOOD
let div = '<div class="test"></div>';   // 文字列中に " があっても混在は禁止
```

**Comment by AT-AT** [comment]
早速の回答ありがとうございます！

> `quotes` ルールは、
>
> * (エスケープの有無にかかわらず) シングルクォートとダブルクォートの文字列を混在させない。どちらかに統一する。
>
> ことを目的としたルールです。(snip)

ルールの目的からすると、エスケープ文字が存在する場合は次のいずれかで対応するという理解で正しいでしょうか？

* 統一不能なので `quotes` ルールを使用しない（シングル・ダブルクォートを許可）
* エスケープ文字を含む文字列はテンプレートリテラルなどの別の方法で表現する

**Comment by mysticatea** [comment]
そうですね。"エスケープ文字の存在に応じてスタイルを変更する" というのはとてもマイナーな嗜好なので、独自ルールを作成してみるのをお勧めします。

**Comment by AT-AT** [comment]
了解です、色々とありがとうございました！
