### ISSUE TITLE
babel-preset-react使用時、無視される変数h1について警告を出したい

### ISSUE THREAD

**Issue by 59naga** [eslint/eslint-jp#5]
こんにちは、ご無沙汰しております。

`styled-components`を使用していて気づいたんですが、以下のようなコードは動作しません。

```jsx
import React from 'react';
import styled from 'styled-components';

const h1 = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;

const App = () => (
  <h1>hello</h1>
);
```
↓

```js
/// ...
var App = function App() {
  return _react2.default.createElement(
    'h1',
    null,
    'hello'
  );
};
```

定義した`h1`は無視され、文字列の`h1`が適用されます。
当たり前といえば当たり前なんですが、これは徹夜でデザインしているときには気づきにくい結果だと思います。`webpack-dev-server`でごりごり書いてる時など、cssが悪いのかjsが悪いのか画面を見ただけでは非常に判断しづらいです。（いわゆるfool-proofですが）

`globals: h1: true`などで定義しておけば警告くらいは出るかと思いましたが、`eslint`や`eslint-plugin-react`のルールで要件に該当するものを見つけられませんでした。

**Comment by mysticatea** [comment]
ふむ。

私は React にはあまり詳しくないのですが、この場合

```jsx
import React from 'react';
import styled from 'styled-components';

const h1 = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;

const App = () => (
  <h1>hello</h1>
);
```

変数 `h1` は未使用変数になりませんか?
もし使用済みと判定されるとしたら、[eslint-plugin-react/jsx-use-vars](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md) ルールのバグのように思います。

**Comment by 59naga** [comment]
いいえ、エラー無しでした。
[yannickcr/eslint-plugin-react](/yannickcr/eslint-plugin-react) のバグとして[報告しました](https://github.com/yannickcr/eslint-plugin-react/issues/1840)。
