### ISSUE TITLE
ESLintのASTを眺めるにはなにがいいのか

### ISSUE THREAD

**Issue by tyankatsu0105** [eslint/eslint-jp#8]
お久しぶりです。

parserとASTについて興味が出ていて今調べてるんですが、こちらの記事がヒットしまして。
https://efcl.info/2016/03/06/ast-first-step/

記事自体が3年前なので今が追えてないので質問させてください。

- ESLintのparserは現在もespreeベースの独自に機能を足したparserを使っているのか
- ESLintのルールを作成したいとき、https://astexplorer.net/ と https://eslint.org/parser/ どちらを見ると良いのでしょうか？

**Comment by mysticatea** [comment]
お久しぶりです。

> - ESLintのparserは現在もespreeベースの独自に機能を足したparserを使っているのか

Yes. 件の記事から状況はまったく変わっていません。

`eslint-plugin-vue` の場合は `espree` の代わりに `vue-eslint-parser` を利用しますが、スクリプト部分は `espree` と等価です (内部的に `espree` を使っています)。AST の仕様は https://github.com/mysticatea/vue-eslint-parser/blob/master/docs/ast.md にあります。

> - ESLintのルールを作成したいとき、https://astexplorer.net/ と https://eslint.org/parser/ どちらを見ると良いのでしょうか？

https://astexplorer.net/ が便利ですね。残念ながら、`vue-eslint-parser` には対応していませんが...。

**Comment by tyankatsu0105** [comment]
なるほど。
では、https://astexplorer.net/ でespreeにするとESLintのASTと同じものが確認できるということですね。でも、`vue-eslint-parser`を使う場合は厳密にはASTが異なると。


@mysticatea さんはvueのparse結果を確認したい場合は、`vue-eslint-parser` で渡ってくるASTをログに出して確認してるのでしょうか？
どのようにvueのASTを確認しながらルールを作っているのか気になります。

**Comment by mysticatea** [comment]
> @mysticatea さんはvueのparse結果を確認したい場合は、vue-eslint-parser で渡ってくるASTをログに出して確認してるのでしょうか？

私はもう見れば分かるので、確認したくなることがないですね...。数年前は https://astexplorer.net/ を酷使していましたが、まだ Vue のパーサーは作ってなかったです。

パーサー自体のバグ修正時には確認したいですが、そこではテストケースを書けば JSON ファイルに自動で出てくるようになってます (テストはその JSON ファイルとの差がない事を確認するようになってる)。

それとは別に、ちょっとした動作確認をしたいことはよくあるので、私はよく `test.js` 書いて動かしたりします。そのため、私のリポジトリの `.gitignore` には必ず `test.js` を無視するように書いています (例: https://github.com/mysticatea/event-target-shim/blob/master/.gitignore#L5)。

**Comment by tyankatsu0105** [comment]
なるほど！
諸々参考にさせていただきます。
ありがとうございました。
またお願いします。
