### ISSUE TITLE
metaのtypeについて

### ISSUE THREAD

**Issue by tyankatsu0105** [eslint/eslint-jp#9]
https://eslint.org/docs/developer-guide/working-with-rules-new#rule-basics
を見ると、`meta`のプロパティには`type`が無いにもかかわらず、`eslint-plugin-vue`には`type`が記載されてます。

古いドキュメントには記載があるので、
https://eslint.org/docs/developer-guide/working-with-rules#rule-basics

typeはもう使わなくていいものなのでしょうか？
`eslint-plugin-vue`で使っている理由ご存知であれば教えてほしいです。

**Comment by mysticatea** [comment]
うん? https://eslint.org/docs/developer-guide/working-with-rules-new てページは初めて見ました。なんだこれ...。そのページはどこからもリンクされていないはず...です。

https://eslint.org/docs/developer-guide/working-with-rules のほうが正しいです。

**Comment by mysticatea** [comment]
紛らわしいので `-new` ページは削除しま~~す~~した (https://github.com/eslint/eslint.github.io/pull/533)
